### ISSUE TITLE
Menu Items getting disappear while I enabled animation true

### ISSUE THREAD

**Issue by Fenscode** [shiburagi/Drawer-Behavior-Flutter#10]
Hi @shiburagi,

You did marvellous works. 
I loved your creation but I found one issue in **Drawer-Behaviour-Flutter** library. When I enabled `animation: true` then the menu item animated while drawer open/close and its looks pretty. But, when I scrolled down from the right side then menu items getting disappear. Here, I have attached one video that's explaining the issue.

[https://vimeo.com/374126583](url)

**Comment by trademunch** [comment]
Any update on this? 
@Fenscode, @shiburagi 

I am getting similar error

The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.


E/flutter (10015): #6      _MenuViewState.setSelectedRenderBox (package:drawerbehavior/menu_screen.dart:54:34)

E/flutter (10015): #7      _AnimatedMenuListItemState.updateSelectedRenderBox (package:drawerbehavior/menu_screen.dart:378:12)
