### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Zumbalamambo** [shiburagi/Drawer-Behavior-Flutter#14]
It throws the following error

> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
> The following dependencies do not satisfy the required version:
> project ':drawerbehavior' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>

**Comment by shiburagi** [comment]
I push new version 0.0.9, maybe U can try and test it now.
