### ISSUE TITLE
Dynamic List not working in builder

### ISSUE THREAD

**Issue by thekavak** [shiburagi/Drawer-Behavior-Flutter#24]
Hi, Thank you for this package.
I added this package my project, it works perfectly but I have a big problem. :) 

As I scrolled down the page, I was pulling data again and showing them in the list. 
Now I am drawing data again, but my list in builder is not refreshed. Can I use something different instead of the builder? how can i solve this.

**Comment by shiburagi** [comment]
can u share ur code?
