### ISSUE TITLE
[GlobalKey#ead10 MenuScreen] error

### ISSUE THREAD

**Issue by hoheehohee** [shiburagi/Drawer-Behavior-Flutter#33]
The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [GlobalKey#ead10 MenuScreen]

drawerbehavior: ^1.1.4

**Comment by shiburagi** [comment]
Hi, can u try with this version 
```yaml
drawerbehavior: ^1.2.2
```
