### ISSUE TITLE
After update flutter i get this error when application run

### ISSUE THREAD

**Issue by KuldipsinhParmar** [shiburagi/Drawer-Behavior-Flutter#35]
![image](https://user-images.githubusercontent.com/40591767/107605342-ec298d00-6c58-11eb-8fee-dabab44c77cb.png)

**Comment by shiburagi** [comment]
which flutter version you used?

**Comment by shiburagi** [comment]
if your flutter using beta channel with null-safety, please use following version:
```yaml
drawerbehavior: ^2.0.0
```
