### ISSUE TITLE
 Error: No named parameter with the name 'resizeToAvoidBottomPadding' in latest flutter beta version

### ISSUE THREAD

**Issue by vb-star** [shiburagi/Drawer-Behavior-Flutter#36]
[+3056 ms] ../../../../../Android/flutter/.pub-cache/hosted/pub.dartlang.org/drawerbehavior-1.2.2/lib/drawer_scaffold.dart:276:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
[        ]       resizeToAvoidBottomPadding: widget.resizeToAvoidBottomPadding,

Details of flutter and SDK:
Flutter is already up to date on channel beta
Flutter 1.26.0-17.5.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 1fe38dcb5f (5 days ago) • 2021-02-10 16:25:47 -0800
Engine • revision d4453f6018
Tools • Dart 2.12.0 (build 2.12.0-259.9.beta)

reference for latest drawerbehavior 
https://pub.dev/packages/drawerbehavior/install

**please fixed asap.**

**Comment by vb-star** [comment]
I think flutter can discontinue  "resizeToAvoidBottomPadding" in the latest version. please change it with "resizeToAvoidBottomInset" or remove it.

**Comment by shiburagi** [comment]
if your flutter using beta channel with null-safety, please use following version:
```yaml
drawerbehavior: ^2.0.0
```
