### ISSUE TITLE
iOS build failing

### ISSUE THREAD

**Issue by guyzk** [shiburagi/Drawer-Behavior-Flutter#4]
`/ios/Pods/Headers/Public/drawerbehavior/DrawerbehaviorPlugin.h:1:9: 
error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
        ^
<unknown>:0: error: could not build Objective-C module 'drawerbehavior'`

**Comment by guyzk** [comment]
Local issue

**Comment by guyzk** [comment]
Thought it was a local issue... Still happens

**Comment by shiburagi** [comment]
i will check it

**Comment by guyzk** [comment]
> i will check it

Anything??

**Comment by shiburagi** [comment]
Sorry for late reply.
I try build & run the example app a few time, but I unable to encounter this issue.
What i can suggest, maybe u can try clean the project with `flutter clean`, then rebuild it

**Comment by guyzk** [comment]
Well after struggling with the issue it seems it wasn't the libs fault. closing
