### ISSUE TITLE
MenuItem optimization

### ISSUE THREAD

**Issue by The28AWG** [shiburagi/Drawer-Behavior-Flutter#40]
This is the best Drawer implementation so far. I've been comparing.
But for complete happiness, there is not enough opportunity to use the Widget instead of IconData as icons.
And if String is also used Widget will be even better.

**Comment by shiburagi** [comment]
for this moment you can try use ```itemBuilder``` to customize menuItem widget/UI ,
```dart
SideDrawer(
  itemBuilder: (context, menuItem, isSelected) {
    return Container();
  }
);
```

**Comment by shiburagi** [comment]
- [ ] add prefix & suffix attribute on ```MenuItem```

**Comment by The28AWG** [comment]
See https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem-class.html for inspiration

**Comment by shiburagi** [comment]
Is impossible to use icon attribute, then need to use new one, if u can figure out an alternative, maybe can try fork this project and make a PR. Thank u
