### ISSUE TITLE
Add property to change Leading Icon in DrawerScaffold()

### ISSUE THREAD

**Issue by zyllus17** [shiburagi/Drawer-Behavior-Flutter#55]
I want to change the Icon to my desired icon.
When I add my desired icon in the `leading` property in the `AppBar`, I am not able to figure out what should be in the onPressed to open the side drawer.

If you allow the option to change the icon or tell me what should I put in the onPressed, it would be very helpful.

**Comment by shiburagi** [comment]
you can set AppBar by using ```appBar``` prop
```dart
final DrawerScaffoldController controller = DrawerScaffoldController();

DrawerScaffold(
    controller: controller,
    appBar: AppBar(
        leading: InkWell(
            onTap: ()=> controller.toggle(),
            child: Icon(Icons.menu),
        ),
    ),
)
```

more,
https://github.com/shiburagi/Drawer-Behavior-Flutter#customize

**Comment by shiburagi** [comment]
related issue
https://github.com/shiburagi/Drawer-Behavior-Flutter/issues/53
