### ISSUE TITLE
Unable to determine Swift version

### ISSUE THREAD

**Issue by ederjavs** [shiburagi/Drawer-Behavior-Flutter#6]
Helo, the following error appears

`   Launching lib/main.dart on iPhone Xʀ in debug mode...
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `drawerbehavior` from `.symlinks/plugins/drawerbehavior/ios`
    Resolving dependencies of `Podfile`
    Comparing resolved specification to the sandbox manifest
      A Flutter
      A drawerbehavior
    Downloading dependencies
    -> Installing Flutter (1.0.0)
    -> Installing drawerbehavior (0.0.1)
      - Running pre install hooks
[!] Unable to determine Swift version for the following pods:
    - `drawerbehavior` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
 /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:578:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:158:in `install!'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.4/libexec/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8
        
    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.
    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Error running pod install
Error launching application on iPhone Xʀ.
Exited (sigterm)
`

**Comment by arutkayb** [comment]
Same :/

**Comment by jaysavsani07** [comment]
I was facing the same issue and had no luck for couple of days then I tried this one which was posted in another repo's issue and seems working perfect with **Xcode 11 & SWIFT 5**


1. Bridging Header must be created.
Open the project with XCode. Then choose `File -> New -> File -> Swift File`.
A dialog will be displayed when creating the swift file (You can use any name of file, it'll not be used anywhere). XCode will ask you if you wish to create **Bridging Header**, click yes.
2. Make sure you have **use_frameworks!** in the Runner block, in ios/Podfile。
3. Make sure you have **SWIFT_VERSION 5.0** selected in you XCode -> Build Settings (When you create new swift file, it'll automatically get added if not there previously. Don't worry)
4. Do **`flutter clean`**
5. Go to your ios folder, delete` Podfile.lock` and Pods folder and then execute **`pod install --repo-update`**
6. Now run **`flutter run`**

Hope it'll help you guys @arutkayb @ederjavs

**Comment by shiburagi** [comment]
#17
