### ISSUE TITLE
Menu Controller import issue

### ISSUE THREAD

**Issue by zzzaJ** [shiburagi/Drawer-Behavior-Flutter#65]
I am getting this error message when trying to build for a iOS app. Any advice?

Error: 'MenuController' is imported from both 'package:drawerbehavior/src/drawer_scaffold.dart' and 'package:flutter/src/material/menu_anchor.dart'.

**Comment by jonex41** [comment]
the issue is the menuController present in the lib and material class
use this forked file
drawerbehavior:
    git: 
      url: https://github.com/jonex41/Drawer-Behavior-Flutter
      ref: dcadea554492b5a7f99a5492962206cf7392cd00

**Comment by shiburagi** [comment]
sorry for late response, you may try with version `2.3.1-dev.1`
