### ISSUE TITLE
flutter v3.22 error

### ISSUE THREAD

**Issue by FurkanArslanF** [shiburagi/Drawer-Behavior-Flutter#68]
The getter 'subtitle1' isn't defined for the type 'TextTheme'.

**Comment by elirehema** [comment]
@shiburagi this can be resolved by replacing .subtitle1 with .titleMedium in side_drawer.dart line 494. Kindly assist

**Comment by shiburagi** [comment]
#69

**Comment by shiburagi** [comment]
latest version should availble now on pub.dev, thanks to @anjarnaufals 
https://github.com/shiburagi/Drawer-Behavior-Flutter/actions/runs/9496345398/job/26170530920

**Comment by anjarnaufals** [comment]
I'm glad I could help out. @shiburagi
